### ISSUE TITLE
Revert back to regular Beef-XSS config when ending script

### ISSUE THREAD

**Issue by AutinDroid** [B4ckP0r7/RogueSploit#2]
First of all, I would like to say that this is a fantastic tool! The only downside is that it changes the beef configs, and never reverts back, so the only way to use beef is via RogueSploit. Making RogueSploit revert to the original configuration at the end of the script would be a nice addtition.

**Comment by B4ckP0r7** [comment]
alright i'll add it! Thanks for the hint :D

**Comment by B4ckP0r7** [comment]
Added resetting to default settings for beef & mitmf's configs.
