### ISSUE TITLE
Failed to stop hostapd.service: Unit hostapd.service not loaded.

### ISSUE THREAD

**Issue by 007scorpio** [B4ckP0r7/RogueSploit#4]

**Comment by B4ckP0r7** [comment]
i think this is ok;
do you have hostapd installed?
if yes, does the fake ap start?
please enable the debug by removing the ->#<- into RogueSploit script from line 29 to 34 and share it.

**Comment by B4ckP0r7** [comment]
closing issue due to no response, for any other problems or bugs please create new issue.
This problem should be caused by no presence of hostapd service running, so it's not a bug itself.

**Comment by jjakosta** [comment]
hello H0nus' I have the following problem RogueSploit failed to start hostapd services unit hostpad services masked.
